RwOrders/Controllers/UserAdminController.cs
using Microsoft.AspNet.Identity.Owin;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using RwOrders.Models;
using Microsoft.AspNet.Identity;

namespace RwOrders.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UserAdminController : Controller
    {
        public UserAdminController()
        {
        }

        public UserAdminController(ApplicationUserManager userManager, ApplicationRoleManager roleManager)
        {
            UserManager = userManager;
            RoleManager = roleManager;
        }

        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        private ApplicationRoleManager _roleManager;
        public ApplicationRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        }

        public async Task<ActionResult> Index()
        {
            return View(await UserManager.Users.OrderBy(o => o.LastName).ThenBy(t => t.FirstName).ToListAsync());
        }

        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var user = await UserManager.FindByIdAsync(id);
            ViewBag.RoleNames = await UserManager.GetRolesAsync(user.Id);
            return View(user);
        }

        public async Task<ActionResult> Create()
        {
            //Get the list of Roles
            ViewBag.RoleId = new SelectList(await RoleManager.Roles.ToListAsync(), "Name", "Name");
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create(RegisterViewModel userViewModel, params string[] selectedRoles)
        {
            if (ModelState.IsValid)
            {
                string password = Functions.PasswordManager.Generate();
                var user = new ApplicationUser
                {
                    UserName = userViewModel.Email,
                    Email = userViewModel.Email,
                    FirstName = userViewModel.FirstName,
                    LastName = userViewModel.LastName
                };
                IdentityResult adminResult = await UserManager.CreateAsync(user, password);

                //Add User to the selected Roles 
                if (adminResult.Succeeded)
                {
                    string html = $@"<div style={"\""}font-family: Arial, Helvetica, sans-serif; font-size: small;{"\""}>
    <p>Hello {user.FirstName}</p>
    <p>You have been granted access to <a href={"\""}https://orders.example.com{"\""}>Widgets Co Orders</a> using the credentials below.</p>
    <table style={"\""}font-family: Arial, Helvetica, sans-serif; font-size: small;{"\""}>
        <tr>
            <th style={"\""}padding: 8px; border-bottom: 1px solid #ddd; text-align:left{"\""}>Website:</th>
            <td style={"\""}padding: 8px; border-bottom: 1px solid #ddd;{"\""}><a href={"\""}https://orders.example.com{"\""}>https://orders.example.com</a></td>
        </tr>
        <tr>
            <th style={"\""}padding: 8px; border-bottom: 1px solid #ddd; text-align:left{"\""}>Email:</th>
            <td style={"\""}padding: 8px; border-bottom: 1px solid #ddd;{"\""}>{user.Email}</td>
        </tr>
        <tr>
            <th style={"\""}padding: 8px; border-bottom: 1px solid #ddd; text-align:left{"\""}>Password:</th>
            <td style={"\""}padding: 8px; border-bottom: 1px solid #ddd;{"\""}>{password}</td>
        </tr>
    </table>
</div>";
                    await UserManager.SendEmailAsync(user.Id, "Vision Login Credentials", html);

                    if (selectedRoles != null)
                    {
                        var result = await UserManager.AddToRolesAsync(user.Id, selectedRoles);
                        if (!result.Succeeded)
                        {
                            ModelState.AddModelError("", result.Errors.First());
                            ViewBag.RoleId = new SelectList(await RoleManager.Roles.ToListAsync(), "Name", "Name");
                            return View();
                        }
                    }
                }
                else
                {
                    ModelState.AddModelError("", adminResult.Errors.First());
                    ViewBag.RoleId = new SelectList(RoleManager.Roles, "Name", "Name");
                    return View();

                }
                return RedirectToAction("Details", new { id = user.Id });
            }
            ViewBag.RoleId = new SelectList(RoleManager.Roles, "Name", "Name");
            return View();
        }

        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var user = await UserManager.FindByIdAsync(id);
            if (user == null)
                return HttpNotFound();

            var userRoles = await UserManager.GetRolesAsync(user.Id);

            return View(new EditUserViewModel()
            {
                Id = user.Id,
                Email = user.Email,
                FirstName = user.FirstName,
                LastName = user.LastName,
                RolesList = RoleManager.Roles.ToList().Select(x => new SelectListItem()
                {
                    Selected = userRoles.Contains(x.Name),
                    Text = x.Name,
                    Value = x.Name
                })
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Email,Id,FirstName,LastName")] EditUserViewModel editUser, params string[] selectedRole)
        {
            if (ModelState.IsValid)
            {
                var user = await UserManager.FindByIdAsync(editUser.Id);
                if (user == null)
                    return HttpNotFound();

                user.UserName = editUser.Email;
                user.Email = editUser.Email;
                user.FirstName = editUser.FirstName;
                user.LastName = editUser.LastName;

                var userRoles = await UserManager.GetRolesAsync(user.Id);

                selectedRole = selectedRole ?? new string[] { };

                var result = await UserManager.AddToRolesAsync(user.Id, selectedRole.Except(userRoles).ToArray<string>());

                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                result = await UserManager.RemoveFromRolesAsync(user.Id, userRoles.Except(selectedRole).ToArray<string>());

                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                return RedirectToAction("Details", new { id = user.Id });
            }
            ModelState.AddModelError("", "Something failed.");
            return View();
        }

        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var user = await UserManager.FindByIdAsync(id);
            if (user == null)
                return HttpNotFound();
            return View(user);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string id)
        {
            if (ModelState.IsValid)
            {
                if (id == null)
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                var user = await UserManager.FindByIdAsync(id);
                if (user == null)
                    return HttpNotFound();
                var result = await UserManager.DeleteAsync(user);
                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

RwOrders/Views/UserAdmin/Create.cshtml
@model RegisterViewModel
@{
    ViewBag.Title = "Create User";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Create", "UserAdmin", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <h4>Create a new account.</h4>
    <hr />
    @Html.ValidationSummary("", new { @class = "text-error" })

    <div class="form-group">
        @Html.LabelFor(m => m.FirstName, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.FirstName, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.LastName, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.LastName, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
        </div>
    </div>

    @*<div class="form-group">
        @Html.LabelFor(m => m.Password, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.ConfirmPassword, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control" })
        </div>
    </div>*@

    <div class="form-group">
        <label class="col-md-2 control-label">Select User Role</label>
        <div class="col-md-10">
            @foreach (var item in ((SelectList)ViewBag.RoleId).OrderBy(r => r.Value))
            {
                <div class="checkbox">
                    <label>
                        <input type="checkbox" name="SelectedRoles" value="@item.Value" />
                        @item.Value
                    </label>
                </div>
            }
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Create" />
        </div>
    </div>
}
<p>
    @Html.ActionLink("Back to list", "Index")
</p>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RwOrders/Views/UserAdmin/Delete.cshtml
@model ApplicationUser

@{
    ViewBag.Title = "Delete";
}

<h2>Delete User</h2>

<h3>Are you sure you want to delete this User?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>@Html.DisplayNameFor(m => m.FullName)</dt>
        <dd>@Html.DisplayFor(m => m.FullName)</dd>

        <dt>@Html.DisplayNameFor(m => m.Email)</dt>
        <dd>@Html.DisplayFor(m => m.Email)</dd>
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Cancel", "Details", new { id = Model.Id })
        </div>
    }
</div>

RwOrders/Views/UserAdmin/Details.cshtml
@model ApplicationUser

@{
    ViewBag.Title = "User Details";
}

<h2>@ViewBag.Title</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>@Html.DisplayNameFor(m => m.FullName)</dt>
        <dd>@Html.DisplayFor(m => m.FullName)</dd>

        <dt>@Html.DisplayNameFor(m => m.Email)</dt>
        <dd>@Html.DisplayFor(m => m.Email)</dd>

        <dt>@Html.DisplayNameFor(m => m.LastVisit)</dt>
        <dd>@Html.DisplayFor(m => m.LastVisit)</dd>

        <dt>@Html.DisplayNameFor(m => m.LastPage)</dt>
        <dd>@Html.DisplayFor(m => m.LastPage)</dd>

        <dt>@Html.DisplayNameFor(m => m.LastBrowser)</dt>
        <dd>@Html.DisplayFor(m => m.LastBrowser)</dd>

        <dt>@Html.DisplayNameFor(m => m.LastIP)</dt>
        <dd>@Html.DisplayFor(m => m.LastIP)</dd>

        <dt>@Html.DisplayNameFor(m => m.NumberOfVisits)</dt>
        <dd>@Html.DisplayFor(m => m.NumberOfVisits)</dd>
    </dl>
</div>
<h4>List of roles for this user</h4>
@if (ViewBag.RoleNames.Count == 0)
{
    <hr />
    <p>No roles found for this user.</p>
}

<table class="table">

    @foreach (var item in ViewBag.RoleNames)
    {
        <tr>
            <td>
                @item
            </td>
        </tr>
    }
</table>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Delete", "Delete", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

RwOrders/Views/UserAdmin/Edit.cshtml
@model EditUserViewModel

@{
    ViewBag.Title = "Edit User";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(m => m.Id)

        <div class="form-group">
            @Html.LabelFor(m => m.FirstName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.FirstName, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.FirstName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.LastName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.LastName, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.LastName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.Email, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Email)
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Roles", new { @class = "control-label col-md-2" })
            <span class=" col-md-10">
                @foreach (var item in Model.RolesList)
                {
                    <input type="checkbox" name="SelectedRole" value="@item.Value" checked="@item.Selected" class="checkbox-inline" />
                    @Html.Label(item.Value, new { @class = "control-label" })
                }
            </span>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Cancel edit", "Details", new { id = Model.Id })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RwOrders/Views/UserAdmin/Index.cshtml
@model IEnumerable<ApplicationUser>

@{
    ViewBag.Title = "Manage Users";
}

<h2>@ViewBag.Title</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table table-hover table-striped">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(m => m.FullName)</th>
            <th>@Html.DisplayNameFor(m => m.Email)</th>
            <th class="text-center hidden-xs">@Html.DisplayNameFor(m => m.NumberOfVisits)</th>
            <th class="text-center hidden-xs">@Html.DisplayNameFor(m => m.LastVisit)</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.ActionLink(Html.DisplayFor(m => item.FullName).ToHtmlString(), "Details", new { id = item.Id })</td>
                <td>@Html.DisplayFor(m => item.Email)</td>
                <td class="text-center hidden-xs">@Html.DisplayFor(m => item.NumberOfVisits)</td>
                <td class="text-center hidden-xs">@Html.DisplayFor(m => item.LastVisit)</td>
            </tr>
        }
    </tbody>
</table>